### ISSUE TITLE
Publish plugin version 2.2.0

### ISSUE THREAD

**Issue by Hc747** [liquibase/liquibase-gradle-plugin#116]
The documentation has been updated to include plugin version `2.2.0` as of March 4th, 2023, however, no release has been created as of yet, effectively meaning Gradle `8.0.+` is still unusable.

**Comment by Hc747** [comment]
@stevesaliman

**Comment by Hc747** [comment]
Bump @stevesaliman

**Comment by fleboulch** [comment]
Following this [commit](https://github.com/liquibase/liquibase-gradle-plugin/commit/b62b5d0f527bc0dc2eb85001655e1fc9fdb4aae3) should you rather release a `3.0.0` version instead of a `2.2.0` as there is breaking changes?

**Comment by stevesaliman** [comment]
I was thinking about that...

I decided to go with a 2.2 release instead of 3.0 because for many, it won't have a breaking change.  I think there are few that still using versions of gradle older than 6.4, and most people have probably updated to the new plugin id as well.  I was thinking that a 3.0. release was more suited for a release that would definitely cause everyone to break.  for example if I renamed "activities" in the extension to something else, it would be a guaranteed breaking change.

**Comment by stevesaliman** [comment]
> The documentation has been updated to include plugin version `2.2.0` as of March 4th, 2023, however, no release has been created as of yet, effectively meaning Gradle `8.0.+` is still unusable.

I'm planning on doing a release this weekend.  I wanted to give folks a chance to provide any feedback on the current state of the code.

**Comment by Hc747** [comment]
@stevesaliman would it be possible to release 2.2.0 and then incorporate feedback into subsequent releases? 2.2.X, etc.

**Comment by stevesaliman** [comment]
2.2.0 has now been released.  Happy gradling!
