### ISSUE TITLE
System properties support

### ISSUE THREAD

**Issue by SButterfly** [liquibase/liquibase-gradle-plugin#20]
Hello,
are there any system property support? like in maven plugin:
```xml
                <configuration>
                    <driver>oracle.jdbc.driver.OracleDriver</driver>
                    <url>${jdbc.url}</url>
                    <username>${jdbc.username}</username>
                    <password>${jdbc.password}</password>
                    <systemProperties>
                        <oracle.net.tns_admin>src/liquibase/</oracle.net.tns_admin>
                        <need-check>${need-check}</need-check>
                    </systemProperties>
                </configuration>
```

Currently I add such hack:
```groovy
project.tasks.findAll { it.name.startsWith(project.liquibaseTaskPrefix) }.each {
    it.doFirst {
        System.setProperty('oracle.net.tns_admin', 'src/liquibase/')
    }
}
```

**Comment by SButterfly** [comment]
ok, I found this lines of code: https://github.com/liquibase/liquibase-gradle-plugin/blob/master/src/main/groovy/org/liquibase/gradle/LiquibaseTask.groovy

But, when I set parameters, system environment doesn't set:
```
       dev {
            changeLogFile "${projectDir}/src/sql/changelog.xml"
            url 'jdbc:oracle:thin:@dev.company.ru'
            username 'login'
            password 'pass'
            parameters=['oracle.net.tns_admin': "${projectDir}/src/sql"]
        }
```

I guess I't because liquibase run in the same process, as gradle task: https://github.com/liquibase/liquibase-gradle-plugin/blob/master/src/main/groovy/org/liquibase/gradle/LiquibaseTask.groovy#L97

**Comment by stevesaliman** [comment]
There is a difference between a Java system property and a Liquibase changelog parameter.  System properties are available to anything running inside the JVM.  Changelog parameters are a map used by Liquibase itself to perform substitutions as it processes the changelogs.  

To set a changelog parameter, I need to pass it to Liquibase with the ```-D``` option so that Liquibase will see it.  Liquibase's choice of -D is somewhat unfortunate because it leads to the impression that it sets system properties, and Liquibase doesn't pay any attention to system properties.

I'm not sure what the maven plugin does, but if I was to make a guess, it probably converts the ```<systemProperties>``` section into changelog parameters like the Gradle plugin does.

If you really need to use system properties instead of changelog parameters like your example above, it wouldn't be too hard to have the build.gradle file read system properties and convert them into parameters.

**Comment by anil-bijlwan** [comment]
@stevesaliman I was looking for a solution using liquibase-maven-plugin using simple java app but not able to achieve.
I want to enable liquibase for Oracle DB deployment using ssl(TCPS), to make it work simply need to set some jvm args with keystore and trustore  which is not the case as maven can't set jvm args/not sure since jvm doesn't come into picture.

Is this feasible that by using liquibase gradle plugin I can authenticate oracle secure DB with jvm args?? I have done this authentication through spring boot liquibase autoconfigure but that is not built to provide all liquibase feature like rollback, diff etc.
