### ISSUE TITLE
Prefix all task names with XXX (e.g. liquibase)

### ISSUE THREAD

**Issue by fedotxxl** [liquibase/liquibase-gradle-plugin#26]
This plugin adds a lot of tasks with common names (like `status`, `update`).... I think this tasks may conflict with other ones... Isn't it better to prefix them?

**Comment by stevesaliman** [comment]
The plugin can already do this with the ```liquibaseTaskPrefix``` option.  For example, if Gradle is invoked with ```-PliquibaseTaskPrefix=liquibase```, or you put ```liquibaseTaskPrefix=liquibase``` in gradle.properties then this plugin will create tasks named liquibaseUpdate, liquibaseTag, etc. instead of update, tag, etc.

The reason this is not the default behavior is because I wanted to preserve backwards compatibility with older versions of the plugin that didn't have the option of prefixing task names.
