### ISSUE TITLE
--verbose issue

### ISSUE THREAD

**Issue by mrfint** [liquibase/liquibase-gradle-plugin#3]
While executing command:

`gradle -PliquibaseCommandValue=--verbose status`

I have this error message every time when I use changeLogParameters in my Activity

`unexpected command parameters [--verbose=-Dliquibase.appUserRole=UserRole]`

_liquibase.appUserRole_ - it is my parameter from 
activities {
  changeLogParameters('liquibase.appUserRole' : someParameter)
}

Without changeLogParameters property everything works ok

**Comment by stevesaliman** [comment]
Thank you for reporting this issue in the new repository.

It turns out this is a bug with Liquibase itself.  I've reported [JIRA 2519](https://liquibase.jira.com/browse/CORE-2519) against the Liquibase project for the bug.  When that gets fixed, this should be a simple matter of bumping the version of Liquibase we use in the plugin.

**Comment by stevesaliman** [comment]
A workaround for the core Liquibase bug has recently been posted to the Liquibase Jira.  I'm going to add this workaround to the Liquibase plugin and release a new version, hopefully in a few days.

**Comment by stevesaliman** [comment]
Release 1.2.2 is out, and fixes this issue.

**Comment by stevesaliman** [comment]
Release 1.2.2 has a bug, and should not be used.  Use version 1.2.3 instead.
