### ISSUE TITLE
-Plabels is not being picked up and applied

### ISSUE THREAD

**Issue by rxcanavan** [liquibase/liquibase-gradle-plugin#31]
I'm trying to run some sql formatted changeset that have labels.  I only want to run update for the passed in label, but liquibase is always running for all.

I'm on 1.2.4:
`classpath 'org.liquibase:liquibase-gradle-plugin:1.2.4'
`

Inside my main task I'm setting:
```
            if (project.hasProperty('labels')) {                
                labels labels
            }    
```

command is essentially:
`gradle -Penv=prod update -Plabels=dwc001_query_log_1.0 -Pcontexts=ETL `

If I print out the label inside build.gradle, I cann see it's there, but it doesn't seem to be applied.  This same approach works fine for the contexts though.

this is how my sql changesets are setup:

`--changeset my_email_address:creation_of_dwc001_query_log_raw context:ETL labels:dwc001_query_log_1.0 
`

Thanks!

**Comment by stevesaliman** [comment]
Sorry it took so long for me to look into this....

A couple of things come to mind.  I'm not sure what groovy will do when it tries to call a method that has the same name as a variable.  I wonder what happens if you use `labels project.ext.labels` instead of just `labels labels`  Or perhaps the project property could have a different name.

The bottom line is that we want to make sure the labels are passed on to Liquibase when it runs.  If you add the `--debug` flag to the gradlew command, the plugin will output the arguments it actually passes to Liquibase.  If the labels are indeed passed to Liquibase, the problem is probably in the change sets themselves.  If the labels are missing, the solution is probably in the if statement you mentioned above.  You could also try updating the plugin to see if it handles passing options to Liquibase better.  I tested this using version 2.0.1

**Comment by stevesaliman** [comment]
Closed due to inactivity.  If this is still an issue with newer versions of the plugin and Liquibase, we can open a new issue.
