### ISSUE TITLE
Support Liquibase 3.4.1

### ISSUE THREAD

**Issue by DKroot** [liquibase/liquibase-gradle-plugin#4]
Liquibase 3.4 has some nice improvements. Can the plug-in be updated to use Liquibase 3.4.1?

**Comment by stevesaliman** [comment]
I should be able to do that.  I'll take a look at it when I get a chance, but it might be next weekend before I get some time.

**Comment by DKroot** [comment]
Thanks, it would be appreciated.

**Comment by stevesaliman** [comment]
It turns out this is not as simple as bumping a version number.  I need to deal with changes to the liquibase's internal API so that the code runs, then I need to look at what was added to Liquibase since the last release, adding support for new tags and command options.

My job is not made easier by the fact that the Liquibase documentation is not always kept up to date :-)

I've got the first part done, I'll work on the second part over the next few days as I get time.

**Comment by DKroot** [comment]
Thanks for the update! I'm watching all developments.

**Comment by stevesaliman** [comment]
Version 1.2.0 of the plugin has been released, and should work with almost all the features of Liquibase 3.4.2.

The only known incompatibility, is that the Groovy DSL doesn't support ```whereParam``` elements in ```update``` or ```delete``` changes.
