### ISSUE TITLE
Error with resolving org.liquibase.gradle plugin dependency

### ISSUE THREAD

**Issue by Al-Hashimi** [liquibase/liquibase-gradle-plugin#43]
Hi,
I am using gradle liquibase plugin version 1.2.4 with gradle version: 4.8.1 as part of the build  process , but today after cleaning caches of the local gradle repo, I still getting the following error. Also there are no changes in the proxy configuration or in the firewall. 

Thank you!

Here is the stack trace:

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\..\..\..\..\build.gradle' line: 34

* What went wrong:
Error resolving plugin [id: 'org.liquibase.gradle', version: '1.2.4', apply: false]
> Could not resolve all dependencies for configuration 'xxxxxx'.
   > Could not determine artifacts for org.liquibase.gradle:org.liquibase.gradle.gradle.plugin:1.2.4
      > Could not get resource 'https://plugins.gradle.org/m2/org/liquibase/gradle/org.liquibase.gradle.gradle.plugin/1.2.4/org.liquibase.gradle.gradle.plugin-1.2.4.jar'.
         > Could not HEAD 'https://plugins.gradle.org/m2/org/liquibase/gradle/org.liquibase.gradle.gradle.plugin/1.2.4/org.liquibase.gradle.gradle.plugin-1.2.4.jar'.
            > Connection reset

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
2 actionable tasks: 2 executed

**Comment by stevesaliman** [comment]
I'm not sure why you would get that error.  I do notice that the jar files for plugins don't appear to be stored on the plugin repo mentioned, which makes me wonder if there is something going on with the Gradle repo, but I don't know how it is supposed to work.

You might have better luck using the old syntax, which would search the Maven repos instead of the Gradle ones.  This would also let you use the latest 2.0.0-SNAPSHOT release which will work better than 1.2.4, and will hopefully be released to production in the next couple of weeks as soon as I work around a logging issue.

If you don't want to use the 2.0.0-SNAPSHOT, I recommend using version 1.2.3 to avoid a bug with the way file paths are stored in the internal Liquibase tables that will make it harder to update to 2.0.0 when it is released.

**Comment by stevesaliman** [comment]
Version 2.0.0 has now been released, so you may want to try to use it instead.

**Comment by Al-Hashimi** [comment]
Thanks , I tried the above suggestions but did not solve the problem then I tried the same thing (cleaning local repo) on other machines that have same OS and it worked fine, So, I will close the issue
