### ISSUE TITLE
mainClassName org.liquibase.gradle.OutputEnablingLiquibaseRunner does not work on liquibase 3.7.0

### ISSUE THREAD

**Issue by matteoturra** [liquibase/liquibase-gradle-plugin#61]
I have been using the _mainClassName 'org.liquibase.gradle.OutputEnablingLiquibaseRunner'_ configuration to see log on the console. But after I upgraded liquibase from 3.6.3 to 3.7.0 this settings has no effect anymore.

**Comment by stevesaliman** [comment]
Thanks for raising this issue.  It looks like Liquibase 3.7.0 broke logging again (among other things).  I'll look into it.

**Comment by stevesaliman** [comment]
The underlying problem here is [CORE-3220](https://liquibase.jira.com/browse/CORE-3220).  The `OutputEnablingLiquibaseRunner` was created as an ugly hack to workaround CORE-3220, but that hack no longer works with the changes to Liquibase Logging.  

Ultimately, this needs to be fixed in Liquibase itself.  I've proposed a solution (or at least the start of one) in the Jira, I'm just waiting to see if the core team likes the idea.  If they do, this should fix the problem.  I wouldn't even need a new release of the plugin :-)

**Comment by stevesaliman** [comment]
I've submitted a [Pull Request](https://github.com/liquibase/liquibase/pull/918) to address this issue.  All we need now is for it to be merged into Liquibase, and a new version to be released.

**Comment by denis111** [comment]
3.8.1 release says "Bugfixes in logging and outputFile" but pull request is not merged. But does it helps us?

**Comment by stevesaliman** [comment]
It does look like Logging now works.  I think it shows WAY too much output for "info" mode, but at least now we get output, and we can tweak the amount of output with the `logLevel` argument.

At this point, I think logging issues are now squarely in the realm of Liquibase itself, so I think we should go ahead and close this issue.
