### ISSUE TITLE
diffChangelog drops all tables

### ISSUE THREAD

**Issue by Hennrik** [liquibase/liquibase-gradle-plugin#73]
I am using the `liquibase-gradle` plugin in my Spring application to generate changelog for the difference between my database and JPA entities schema. My running db has tables:
- Table Books
- Table People
- Table Articles

And my entities are like this:

```kotlin
@Entity
@Table(name = "people")
data class Person (
    @Id
    @GeneratedValue(strategy= GenerationType.IDENTITY)
    var id: Long = -1,
    val name: String = "",
    val address: String = ""
)
```

When I run the Gradle command `diffChangelog`, I suppose it will generate a changelog containing only the difference.  However, the generated changelog drops all my tables. 

**generated change log**
```xml
...
<changeSet author="me (generated)" id="1589869503698-63">
        <dropTable tableName="books"/>
    </changeSet>
    <changeSet author="me (generated)" id="1589869503698-64">
        <dropTable tableName="people"/>
    </changeSet>
    <changeSet author="me (generated)" id="1589869503698-65">
        <dropTable tableName="article"/>
    </changeSet>
...
```

Here is part of my `build.gradle`:

```groovy
buildscript {
    repositories {
        ...
    }

    dependencies {
        classpath "org.liquibase:liquibase-gradle-plugin:2.0.2"
        ...
    }
}

apply plugin: 'org.liquibase.gradle'

dependencies {
     ...
    liquibaseRuntime('org.liquibase:liquibase-core')
    liquibaseRuntime('org.liquibase.ext:liquibase-hibernate5:3.6')
    liquibaseRuntime('org.postgresql:postgresql')
    liquibaseRuntime('org.springframework.boo
    ...
}
...
liquibase {
    activities {
        main {
            url "jdbc:postgresql://localhost:5432/mydb"
            username "postgres"
            password "test"
            driver "org.postgresql.Driver"
            changeLogFile "src/main/resources/db/changelog/changelog-diff.xml"
            referenceDriver "liquibase.ext.hibernate.database.connection.HibernateDriver"
            referenceUrl "hibernate:spring:mypackage?dialect=org.hibernate.dialect.PostgreSQLDialect"
        }
    }
}

...
```
Is this a known issue for this plugin? Or I messed the Gradle configurations up?

**Comment by stevesaliman** [comment]
I'm not very familiar with the hibernate extension, or using Liquibase in Spring Boot projects, but there are a couple of things that come to mind.  I'm not sure if the configuration above is exactly what you're trying to use, or if there are some things redacted, but I'd look a the following:

1. There should be a `liquibaseRuntime sourceSets.main.output` dependency to make sure the hibernate extension can find your code
2. There should be a `diffChangeLog.dependsOn compileJava` and maybe `diff.dependsOn compileJava` task dependency to make sure your code is actually compiled before it begins.
3. the referenceUrl should have the fully qualified package name in it.  In otherwords `com.mycompany.myapp.mypackage` instead of just `mypackage`  

Here is what I think is happening....

The diffChangeLog table is supposed to build a changelog that takes the database from its current state to the state represented by your Java code.  The hibernate extension sees your 3 tables, but doesn't see your compiled entities.  As a result, it thinks you shouldn't have any tables, and creates a changelog to drop the 3 tables it saw in the database.

Again, this is just an educated guess.  Does any of that help with your issue?

**Comment by stevesaliman** [comment]
Closed due to inactivity
