### ISSUE TITLE
Support Liquibase 4.4.x command line and properties

### ISSUE THREAD

**Issue by andrew-simmons** [liquibase/liquibase-gradle-plugin#89]
Liquibase 4.4.0 CLI changed most (maybe all) of the command line arguments and properties keys, and the interactive help documents all the values.

The gradle plugin seems to only support the older arguments and keys (even when using liquibase-core 4.4.2). And will fail with an error, if it encounters a 4.4 one. 

As a user of liquibase 4.4.x, I would like to be able to use the same command line arguments and property keys in the gradle plugin that I use with the command line program.

**Comment by stevesaliman** [comment]
Thank you for submitting this issue.  I didn't know Liquibase had rearranged the way the CLI works.

I'll look into making the plugin support the new way of handling arguments as I get time.  Until then, there may be a suitable workaround.

If you add `liquibaseRuntime 'info.picocli:picocli:4.6.1'` to your build.gradle file, and `mainClassName = 'liquibase.integration.commandline.LiquibaseCommandLine'` to the liquibase block of your build.gradle file, the plugin will use the new command line parser to handle arguments.

Note that you'll still have to use camelCase task names and arguments, but they appear to work because of backwards compatibility.

**Comment by stevesaliman** [comment]
Release 2.1.0 now supports Liquibase 4.4.0+, and it chooses the right mainClassName based on the version of Liquibase it finds on the classpath, so the previous workaround involving the mainClassName property is no longer needed, though you do still need to include the picocli library.
