### ISSUE TITLE
updateSQL task ignores outputFile

### ISSUE THREAD

**Issue by andrew-simmons** [liquibase/liquibase-gradle-plugin#90]
Running the updateSQL task always outputs the sql to the console even when the `outputFile` argument is provided. Running  liquibase from the command line with the `outputFile` argument creates the specified file.

liquibase-core 4.4.2
Liquibase command 4.4.1 (homebrew is behind)

As a user of the liquibase gradle plugin, I would like the updateSQL task to write the generated output to the `outputFile` argument when it is specified.

**Comment by caseyscarborough** [comment]
It looks like this works properly in 4.3.x. I tested with 4.3.5 (the latest version on 4.3.x) and it handles the output file as expected.

This might caused by Liquibase changing `--outputFile` to `--output-file` in 4.4.x (see the bottom of the [futureRollbackSQL command page](https://docs.liquibase.com/commands/community/futurerollbacksql.html)).

**Comment by stevesaliman** [comment]
Issue #89 has a workaround that should solve this issue.  Liquibase 4.4.0 heavily changed the way it parses command lines, but they have a class that handles legacy commands and tasks.

**Comment by stevesaliman** [comment]
Release 2.1.0 supports Liquibase 4.4.0+, and respects the outputFile argument.  The `mainClassName` workaround mentioned in #89 is no longer needed, though the dependency on picocli sill is.
