### ISSUE TITLE
Version 2.1.0 is not compatible with Spring's dependency management plugin

### ISSUE THREAD

**Issue by dmoidl** [liquibase/liquibase-gradle-plugin#94]
Hi 👋 

After we upgraded the Liquibase Gradle plugin to version `2.1.0`, the `update` task started failing with
```
Execution failed for task ':update'.
> Liquibase-core was not found  not found in the liquibaseRuntime configuration!
```

even though nothing else in the build file changed (which means we very much still do have `liquibase-core` in the `liquibaseRuntime` configuration). However, as we also use the [Spring dependency management plugin](https://docs.spring.io/dependency-management-plugin/docs/current/reference/html/) we have it configured like so:
```
liquibaseRuntime("org.liquibase:liquibase-core")
```
letting said plugin choose the right version for us.

After examining the the sources I found out this is the root cause the issue: [this check](https://github.com/liquibase/liquibase-gradle-plugin/blob/master/src/main/groovy/org/liquibase/gradle/LiquibaseTask.groovy#L195) always fails in our case as we simply don't have an explicit version stated in the dependency notation.

A workaround is to add the explicit version, but that goes against the spirit of the dependency management plugin (and possibly any other kind of custom dependency management scheme).

**Comment by stevesaliman** [comment]
the problem seems to be with line 186: `classpath.allDependencies` appears to only tell me the version that was *declared*, not the version that will actually be *used*, which is ultimately what the plugin needs to know to choose the correct class to use for processing arguments.

The `gradlew dependencies` command shows the correct version, so I'll need to figure out how to get my plugin task to get that same information.

**Comment by stevesaliman** [comment]
Release 2.1.1 should fix this issue.

**Comment by esselesse** [comment]
@stevesaliman what about 2.2.1?
<img width="2469" alt="image" src="https://github.com/liquibase/liquibase-gradle-plugin/assets/5176168/50bc36f4-197e-4af9-9218-a5a0d8329a6e">
